# Generated by Django 4.2.5 on 2023-10-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Kategoriýa',
                'verbose_name_plural': 'Kategoriýalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('rss_feed', models.URLField()),
                ('title', models.CharField(max_length=500, verbose_name='Titul')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='url')),
                ('pub_date', models.DateTimeField(verbose_name='Goýlan wagty')),
                ('link', models.URLField(verbose_name='Web sahypasy')),
                ('description', models.TextField(verbose_name='Beýany')),
                ('content', models.TextField(verbose_name='Mazmuny')),
                ('image', models.TextField(verbose_name='Suraty')),
                ('thumbnail', models.TextField(verbose_name='Kiçi suraty')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': 'Habar',
                'verbose_name_plural': 'Habarlar',
                'ordering': ['-pub_date'],
            },
        ),
    ]
