# Generated by Django 4.2.5 on 2023-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Mazmuny'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Mazmuny'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_tk',
            field=models.TextField(null=True, verbose_name='Mazmuny'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Beýany'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Beýany'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='Beýany'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Titul'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Titul'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tk',
            field=models.CharField(max_length=500, null=True, verbose_name='Titul'),
        ),
    ]
